// NFS / AFC history — placings, series teams, career games
// Source: NFS_AFC_HISTORY.xlsx. Update once per season.

export type Placing = { season: string; men_rr: string | null; men_final: string | null; women_rr: string | null; women_final: string | null }
export type SeriesTeam = { season: string; grade: 'men' | 'women'; players: string[] }
export type CareerGames = { name: string; games: number }

export const PLACINGS: Placing[] = [
  {"season": "2004-05", "men_rr": null, "men_final": "Dent 'R' Us Ramblers", "women_rr": null, "women_final": null},
  {"season": "2005-06", "men_rr": "Mt Albert Ramblers", "men_final": "Northcote", "women_rr": "Mt Albert Ramblers", "women_final": "Northcote"},
  {"season": "2006-07", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers", "women_rr": "Northcote", "women_final": "Northcote"},
  {"season": "2007-08", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers", "women_rr": "Marist", "women_final": "Mt Albert Ramblers"},
  {"season": "2008-09", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers", "women_rr": "Wait\u0101kere Bears", "women_final": "Mt Albert Ramblers"},
  {"season": "2009-10", "men_rr": "Wait\u0101kere Bears", "men_final": "Wait\u0101kere Bears", "women_rr": "Wait\u0101kere Bears", "women_final": "Wait\u0101kere Bears"},
  {"season": "2010-11", "men_rr": "Mt Albert Ramblers", "men_final": "Auckland United", "women_rr": "Wait\u0101kere Bears", "women_final": "Wait\u0101kere Bears"},
  {"season": "2011-12", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers", "women_rr": "Wait\u0101kere Bears", "women_final": "Mt Albert Ramblers"},
  {"season": "2012-13", "men_rr": "Auckland United", "men_final": "Auckland United", "women_rr": "\u014ct\u0101huhu", "women_final": "\u014ct\u0101huhu"},
  {"season": "2013-14", "men_rr": "Auckland United", "men_final": "Auckland United", "women_rr": "Western Magpies", "women_final": "Western Magpies"},
  {"season": "2014-15", "men_rr": "Roosters", "men_final": "Auckland United", "women_rr": "Marist", "women_final": "Marist"},
  {"season": "2015-16", "men_rr": "Auckland United", "men_final": "Auckland United", "women_rr": "Western Magpies", "women_final": "Western Magpies"},
  {"season": "2016-17", "men_rr": "Auckland United", "men_final": "Auckland United", "women_rr": "Western Magpies", "women_final": "Western Magpies"},
  {"season": "2017-18", "men_rr": "Mt Albert Ramblers", "men_final": "Auckland United", "women_rr": "Wait\u0101kere Bears", "women_final": "Wait\u0101kere Bears"},
  {"season": "2018-19", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers (Rain out)", "women_rr": "Western Magpies", "women_final": "Western Magpies (Rain out)"},
  {"season": "2019-20", "men_rr": "Mt Albert Ramblers", "men_final": "Auckland United", "women_rr": "\u014ct\u0101huhu", "women_final": "\u014ct\u0101huhu"},
  {"season": "2020-21", "men_rr": "Mt Albert Ramblers", "men_final": "Auckland United", "women_rr": "\u014ct\u0101huhu", "women_final": "\u014ct\u0101huhu"},
  {"season": "2021-22", "men_rr": "Auckland United", "men_final": null, "women_rr": "\u014ct\u0101huhu", "women_final": "\u014ct\u0101huhu"},
  {"season": "2022-23", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers", "women_rr": "\u014ct\u0101huhu", "women_final": "\u014ct\u0101huhu"},
  {"season": "2023-24", "men_rr": "Mt Albert Ramblers", "men_final": "Mt Albert Ramblers", "women_rr": "Northern Bandits", "women_final": "Wait\u0101kere Bears"},
  {"season": "2024-25", "men_rr": "AK United", "men_final": "Ramblers Maroon", "women_rr": "Waitakere Bears", "women_final": "Bandits"},
  {"season": "2025-26", "men_rr": "AK United", "men_final": "Auckland United", "women_rr": "Roosters", "women_final": "Roosters"},
]

// Auckland Major Men's champions (pre-NFS heritage)
export const HERITAGE_MEN: { season: string; winner: string }[] = [
  {"season": "1976-77", "winner": "United"},
  {"season": "1977-78", "winner": "United"},
  {"season": "1978-79", "winner": "Metro College"},
  {"season": "1979-80", "winner": "United"},
  {"season": "1980-81", "winner": "Mt Albert Ramblers"},
  {"season": "1981-82", "winner": "Mt Albert Ramblers"},
  {"season": "1982-83", "winner": "Mt Albert Ramblers"},
  {"season": "1983-44", "winner": "Mt Albert Ramblers"},
  {"season": "1984-55", "winner": "Mt Albert Ramblers"},
  {"season": "1985-86", "winner": "Papatoetoe"},
  {"season": "1986-87", "winner": "Mt Albert Ramblers"},
  {"season": "1988-89", "winner": "Marist"},
  {"season": "1989-90", "winner": "Marist"},
  {"season": "1990-91", "winner": "United"},
  {"season": "1991-92", "winner": "Onehunga M\u0101ngere"},
  {"season": "1992-93", "winner": "Marist"},
  {"season": "1993-94", "winner": "Marist"},
]

// Pre-NFS Women's champions
export const HERITAGE_WOMEN: { season: string; winner: string }[] = [
  {"season": "1994-95", "winner": "Ramblers"},
  {"season": "1995-96", "winner": "Ramblers, Papatoetoe"},
  {"season": "1996-97", "winner": "Marist"},
  {"season": "1997-98", "winner": "Marist"},
  {"season": "1998-99", "winner": "Papatoetoe"},
  {"season": "1999-00", "winner": "Papatoetoe"},
]

export const SERIES_TEAMS: SeriesTeam[] = [
  {"season": "2005-06", "grade": "women", "players": ["Michelle Kingi", "Carina Hale", "Mereana Tobenhouse", "Jodi Byles", "Maleme Williams", "Pearl Parsons", "Keira Harkness", "Katie Hetherington", "Jessica Wolferstan", "Tegan Bromhead", "Helen Packer", "Fiona Timu", "Ritua Petero", "Tom Kingi", "John Ball", "Lucy Wikaira"]},
  {"season": "2006-07", "grade": "men", "players": ["Heinie Shannon", "Kim Hansen", "Patrick Shannon", "Leon Hardie", "Lyndon Andrew", "Tai Hiku", "Dylan Tomlin", "Nathan Nukunuku", "Michael Niu", "Gus Ledger", "Des Pemerika", "Thomas Katene", "Jonathon Munden", "Carlaus Te Kawa", "Donny Hale", "Danny Knight", "Tracey Atkin"]},
  {"season": "2006-07", "grade": "women", "players": ["Michal Tangaroa", "Megan Farrell", "Mereana Joseph", "Tina Martens", "Cherie Wihapi", "Courtney Warren", "Pauline Tahuri", "Lisa Hau", "Sina Hunkin", "Ngamoko Hiku", "Lydia Isaac", "Rebecca Bromhead", "Jackie Smith", "John Ball", "Tania Irving"]},
  {"season": "2007-08", "grade": "men", "players": ["Steven Tau", "Thomas Cameron", "Patrick Shannon", "Rodney Caddy", "Scott O'Nealle", "Bobby King", "Alfons Oveinikovas", "Timothy Tuakana-Kapi", "Marty Cannons", "Dean Wallace", "Ryan Croawell", "Ben Enoka", "Jerome Haretuku", "Heinie Shannon", "Jamie Matiu", "Nathan Nukunuku", "Donny Hale", "Dave Boswell", "Tracee Topia"]},
  {"season": "2007-08", "grade": "women", "players": ["Megan Farrell", "Sheree Cartwright", "Mereana Joseph", "Pauline Tahuri", "Casey-Lee Misa", "Kalala Gabriel", "Sabrina Nihoj", "Tuhi Cooper", "Tessa Houkamau", "Jackie Rameka", "Katie Hetherington", "Jane Ale", "Sina Hunkin", "Irene Marr", "Shonelle Wihapi", "Selena Hoani", "Venita Hokai", "John Ball", "Sally Hoani"]},
  {"season": "2008-09", "grade": "men", "players": ["Brad Rona", "Thomas Enoka", "Patrick Shannon", "Lee Rudolph", "Lyndon Andrew", "Kurt Allan", "Leon Lambert", "Tony Niu", "Rod Caddy", "Ben Enoka", "Gus Leger", "Bernard Hale", "Curtis Cosh", "Donny Hale", "Nicky Woon", "Deanna Callaghan"]},
  {"season": "2008-09", "grade": "women", "players": ["Michal Tangaroa", "Megan Farrell", "Lisa Arkell", "Courtney Warren", "Victoria Reyland", "Jenna Woepse", "Rebecca Bromhead", "Michelle Ramea", "Tegan Bromhead", "Heidi Leathart", "Sina Hunkin", "Sheree Cartwright", "Tuhi Cooper", "Kyla Bromhead", "Venita Hokai", "Wayne Roper", "Fran Bromhead"]},
  {"season": "2009-10", "grade": "men", "players": ["Brad Rona", "Heinie Shannon", "Hayden Wildbore", "Patrick Shannon", "Valdermar Terkleson", "Nathan Nukunuku", "Lawrence Naera", "Rueben Topia", "Jason Walker", "Dylan Tomlin", "Ben Enoka", "Michael Niu", "Patrick Shannon", "Tracee Topia", "Gwen Fletcher"]},
  {"season": "2009-10", "grade": "women", "players": ["Courtney Maihi", "Michal Tangaroa", "Anita Leeuw", "Mereana Joseph", "Jarrah Tuoro", "Katie Hetherington", "Victoria Reyland", "Courtney Warren", "Tegan Bromhead", "Tuhi Cooper", "Sina Hunkin", "Kyla Bromhead", "Israel Nukunuku", "Anita Gabriel", "Debbie Townley"]},
  {"season": "2010-11", "grade": "men", "players": ["Brad Rona", "Thomas Enoka", "Kurtis Tomkins", "Hayden Wildbore", "Jason Gerbes", "Gerard Long", "Nick McGregor", "Michael Niu", "Callum Ryan", "Bernard Hale", "Campbell Enoka", "Ben Enoka", "Roman Gabriel", "Duncan Enoka", "Harry Wooding", "Gwen Fletcher"]},
  {"season": "2010-11", "grade": "women", "players": ["Jennifer Feret", "Megan Farrell", "Aloma Ngatokurua", "Courtney O'Donnell", "Rebecca Bromhead", "Michelle Kingi", "Aroha Haretuku", "Te Reo Powhiri Matautia", "Krystal Tourangi", "Kingsley Avery", "Jacquie Stipec", "Heidi Leathart", "Kataraina Hiku", "Wayne Roper", "Sally Hoani", "Priscilla Niuia"]},
  {"season": "2011-12", "grade": "men", "players": ["Thomas Enoka", "Brad Rona", "Patrick Shannon", "Kevin Stockford", "Kurt Allan", "Tony Niu", "Isaac Fletcher", "Jerome Haretuku", "Ben Enoka", "Bernard Hale", "Alfons Oveinikovas", "Nathan Thorpe", "Nathan Nukunuku", "Bronwyn Knight", "Kellie Dormer"]},
  {"season": "2011-12", "grade": "women", "players": ["Michelle Kingi", "Megan Farrell", "Santana Harris", "Rebecca Bromhead", "Katrina Stockford", "Jennifer Feret", "Clarissa Mafoe", "Te Reo Powhiri Matautia", "Tegan Bromhead", "Katie Hetherington", "Michal Tangaroa", "Jaimee-Ann Dick", "Tyneesha Houkamau", "Heidi Leathart", "Venita Hokai", "Fran Bromhead", "Debbie Townley"]},
  {"season": "2012-13", "grade": "men", "players": ["Thomas Enoka", "Brad Rona", "Mark Sorenson", "Nathan Nukunuku", "Josh Kingi", "Paul Doolan", "Mathew Hicks", "Jerome Haretuku", "Ben Enoka", "Joshua Niu", "Callum Ryan", "Aaron Knight", "Duncan Enoka", "Deanna Callaghan", "Christine Nukunuku"]},
  {"season": "2012-13", "grade": "women", "players": ["Michal Tangaroa", "Samantha Parks", "Kaleo Eldredge", "Rebecca Bromhead", "Breanna Gibson", "Victoria Reyland", "Melanie Gallagher", "Brooke Stilwell", "Katie Hetherington", "Tyneesha Houkamau", "Wayne Roper", "Ronnie Gurney", "Annie Martin"]},
  {"season": "2013-14", "grade": "men", "players": ["Campbell Gibson", "Thomas Enoka", "Michael Niu", "Rueben Topia", "Kevy Cannons", "Regan O'Neil", "Alfons Oveinikovas", "Jerome Haretuku", "Ben Enoka", "Michael Gibbs", "Campbell Enoka", "Sam Brown", "Duncan Enoka", "Dirk McGregor", "Gwen Fletcher"]},
  {"season": "2013-14", "grade": "women", "players": ["Samantha Parks", "Michal Tangaroa", "Kaleo Eldredge", "Beth Stavert", "Carina Hale", "Katrina Nukunuku", "Santana Harris", "Aroha Haretuku", "Jennifer Feret", "Mereana Monk", "Katie Hetherington", "Ancelle Van Molendorff", "Tua Raroa", "Fran Bromhead", "Marie Stavert"]},
  {"season": "2014-15", "grade": "men", "players": ["Bayley Hoani", "Heinie Shannon", "Connor Peden", "Kurtis Tomkins", "Rueben Topia", "Cole Evans", "Kirby Roper", "Bernard Hale", "Ben Enoka", "John Hireme", "Vincent Harris", "Nathan Nukunuku", "Duncan Enoka", "Danny Knight", "Karina Rueb"]},
  {"season": "2014-15", "grade": "women", "players": ["Blaire Luna", "Sammi Parks", "Mandy Ogle", "Kaleo Eldredge", "Katrina Nukunuku", "Jennifer Feret", "Kyla Bromhead", "Nita Hickey", "Krysta Hoani", "Mereana Monk", "Ancelle Van Molendorff", "Jaimee-Ann Dick", "Venita Hokai", "Anita Mok", "Debbie Townley"]},
  {"season": "2015-16", "grade": "men", "players": ["Thomas Enoka", "Zane Van Lieshout", "Nathan Nukunuku", "Joshua Kingi", "Cole Evans", "Kurtis Tomkins", "Ben Enoka", "Stuart Reynolds", "Jerome Haretuku", "Taiki Apu", "Curtis Cosh", "Lewis Jerard", "Duncan Enoka", "Danny Knight", "Karina Rueb"]},
  {"season": "2015-16", "grade": "women", "players": ["Jennifer Feret", "Samantha Parks", "Stefanie Smith", "Breanna Gibson", "Kayla Clark", "Ariana Kingi", "Nita Hickey", "Jenny Williams", "Kaleo Eldredge", "Ancelle Van Molendorff", "Rachel Van Veen", "Gillian Wills", "Tua Raroa", "Fran Bromhead", "Marie Stavert"]},
  {"season": "2016-17", "grade": "men", "players": ["Bayley Hoani", "Harrison Valk", "Thomas Enoka", "Cole Evans", "Rueben Topia", "Stuart Reynolds", "Bradley Bennett", "Jerome Haretuku", "Ben Enoka", "Campbell Enoka", "David-Lee Alexander", "Duncan Enoka", "Dirk McGregor", "Gwen Fletcher"]},
  {"season": "2016-17", "grade": "women", "players": ["Jamie Allred", "Loran Parker", "Aaria Tawha", "Jennifer Feret-Brear", "Katrina Nukunuku", "Freya Bullock", "Nita Hickey", "Kalala Gabriel", "Tomoko Goda", "Krysta Hoani", "Samantha Parks", "Stephanie Brunette", "Phil Casey", "Carol Wills", "Priscilla Abraham"]},
  {"season": "2017-18", "grade": "men", "players": ["Pita Rona", "Campbell Gibson", "Taylor Hick", "Brad Rona", "Bobbie King", "Huw Davies", "Cole Evans", "Bradley Bennett", "Vinny Harris", "Max Maoate", "Josh Niu", "Nathan Nukunuku", "Leon Graham", "Duncan Enoka", "Fergus McAlpine", "Gwen Fletcher"]},
  {"season": "2017-18", "grade": "women", "players": ["Samantha Parks", "Alyson Spinas-Valainis", "Kyla Bromhead", "Lisa Maulden", "Tenille Auimatagi", "Brooke Scott", "Katrina Nukunuku", "Kingsley Avery", "Beth Reid", "Krysta Hoani", "Kaleo Eldredge", "Carina Hale", "Dion Nukunuku", "Fran Bromhead", "Priscilla Abraham"]},
  {"season": "2018-19", "grade": "men", "players": ["Campbell Gibson", "Kallan Compain", "Isaac Fletcher", "Brock Attewell", "Pita Rona", "Cole Evans", "Seth Gibson", "Ben Enoka", "Connor Peden", "Logan Esau", "Thomas Enoka", "Nathan Nukunuku", "Kurtis Tomkins", "Steve Collins", "Christine Nukunuku"]},
  {"season": "2018-19", "grade": "women", "players": ["Cheyanne Tarango", "Zoe Tolhopf", "Gretchen Aucoin", "Jennifer Feret-Brear", "Brooklyn Temu", "Lisa Maulden", "Beth Reid", "Krysta Hoani", "Kyla Bromhead", "Pearl-Marli Waetford", "Stephanie Texeira", "Mikayla Cross", "Phil Casey", "Tony Johnston", "Priscilla Abraham"]},
  {"season": "2019-20", "grade": "men", "players": ["Blake Radford", "Bayley Pearson-Hoani", "Kallan Compain", "Brock Attewell", "Gerard Long", "Cole Evans", "Seth Gibson", "Cory Collins", "Ryschan Thompson", "Alfons Oveinikovas", "Quinten Bruce", "Harrison Valk", "Connor Peden", "Pita Rona", "Thomas Enoka", "Garth Pollard", "Christine Nukunuku", "Gwen Fletcher"]},
  {"season": "2019-20", "grade": "women", "players": ["Gretchen Aucoin", "Alyx Bloom", "Zoe Tolhopf", "Logan Moreland", "Lisa Maulden", "Rachel Jackson", "Stephanie Texeira", "Tomoko Goda", "Beth Reid", "Tyneesha Houkamau", "Lily Nielsen", "A'ieesha Hooper", "Caitlin Sill", "Carina Hale", "Tenille Auimatagi", "Jamie Brear", "Shelley Scott", "Priscilla Abraham"]},
  {"season": "2020-21", "grade": "men", "players": ["Daniel Chapman", "Pita Rona", "Max Earley", "Rueben Topia", "Brock Attewell", "Rhys Evans", "Cole Evans", "Connor Peden", "Seth Gibson", "Jerome Haretuku", "Logan Esau", "Traye Wildbore", "Bradley Bennett", "Alfons Oveinikovas", "Te Kirika Cooper-Nicola", "Garth Pollard", "Dirk McGregor", "Gwen Fletcher"]},
  {"season": "2020-21", "grade": "women", "players": ["Loran Parker", "Caitlin Sill", "Alyx Bloom", "Rebecca Bromhead", "Mereana Makea", "Ariana Kingi", "Logan Moreland", "Krysta Hoani", "Brooke Whiteman", "Kayla Clark", "Kyla Bromhead", "Pania Monk", "Carina Hale", "Nita Hickey", "Tara Jeffery", "Sammi Parks", "Fran Bromhead", "Priscilla Abraham"]},
  {"season": "2021-22", "grade": "men", "players": ["Tournament team was not announced due to Covid impacted season"]},
  {"season": "2021-22", "grade": "women", "players": ["Loran Parker", "Alyx Bloom", "Stefanie Smith", "Shyah Hale", "Logan Moreland", "Katrina Nukunuku", "Ocearn Mathews", "Krysta Hoani", "Tyarn Bromhead-Lemalu", "Kayla Clark", "Rebecca Bromhead", "Sarahnaruth Pauga", "Carina Hale", "Tyneesha Houkamau", "Brooke Whiteman", "Sammi Parks", "Priscilla Abraham", "Fran Bromhead"]},
  {"season": "2022-23", "grade": "men", "players": ["Taine Slaughter", "Dallas Amai-Tatu", "Tim Kelly", "Harrison Wildbore", "Cole Evans", "Rhy Evans", "Brock Attewell", "Connor Peden", "Bradley Bennett", "Maddix Rice", "Alfons Oveinikovas", "Jamie Matiu", "Ethan Shannon", "Logan Esau", "Liam Twigden", "Nathan Nukunuku", "Megan Earley", "Gwen Fletcher"]},
  {"season": "2022-23", "grade": "women", "players": ["Loran Parker", "Cassady Knudsen", "Alyx Bloom", "Zoe Tolhopf", "Breanna Gibson", "Katrina Nukunuku", "Logan Moreland", "Babs De Jonge", "Krysta Hoani", "Tyarn Bromhead-Lemalu", "Renee Booth", "Ilaria Cacciamani", "Stephanie Texeira", "Ocearn Mathews", "Shyah Hale", "Sammi Parks", "Priscilla Abraham", "Tania Sampson"]},
  {"season": "2023-24", "grade": "men", "players": ["Dallas Amai Tatu", "Floyd Nola", "Max Earley", "Harrison Wildbore", "Cole Evans", "Rhys Evans", "Brock Evans", "Matthew Oxley", "Bradley Bennett", "Maddix Rice", "Simon McMillan", "Brock Attewell", "Isaac Fletcher", "Oscar Clark", "Blake Wardrope", "Nathan Nukunuku", "Megan Earley", "Gwen Fletcher"]},
  {"season": "2023-24", "grade": "women", "players": ["Cassady Knudsen", "Tyla Morrison", "Sarahnaruth Pauga", "Clover Alapaki", "Ellazay Utanga-Fletcher", "Shyah Hale", "Tyneesha Houkamau", "Kamryn Coleman", "Beth Reid", "Ruby Nola", "Cheyenne Young", "Loran Parker", "Al Spinas-Valainis", "Alyssa Bailey", "Freya Bullock", "Tegan Bromhead", "Kylie Dalton", "Fran Bromhead"]},
  {"season": "2024-25", "grade": "men", "players": ["Taine Slaughter", "Floyd Nola", "Max Earley", "Thomas Enoka", "Ciryl Wilson", "Oscar Clark", "Cole Evans", "Logan Esau", "Logan Newman", "Ben Enoka", "Max Russell", "Traye Wildbore", "Harrison Wildbore", "Ihaka Tangaroa", "Jayden Priestley", "Connor Peden", "Kelvin Roberts", "Megan Earley", "Gwen Fletcher"]},
  {"season": "2024-25", "grade": "women", "players": ["Charlotte Graham", "Kamryn Coleman", "Masona Ando", "Karstein Fuimaono", "Tynessha Houkamau", "Haruka Matsui", "Chloe Malauulu", "Beth Reid", "Tyarn Bromhead Lemalu", "Ruby Nola", "Loran Parker", "Shyah Hale", "Alyx Bloom", "Katrina Nukunuku", "Jessie Jackson", "Rachel Young", "Kylie Dalton", "Debbie Townley"]},
  {"season": "2025-26", "grade": "men", "players": ["Liam Twigden", "Floyd Nola", "Harrison Wildbore", "Isaac Fltcher", "Thomas Enoka", "Oscar Clark", "Brock Evans", "Aaron Dormer", "Ben Enoka", "Jamie Joseph", "Ryan Earley", "Kyle Roberts", "Traye Wildbore", "Jordan Tahana", "Tim Kelly", "Duncan Enoka", "Megan Earley", "Gwen Fletcher"]},
  {"season": "2025-26", "grade": "women", "players": ["Lauren Heijnsdijk", "Carina Hale", "Kiara Lei-Lani Taimai", "Tyarn Bromhead Lemalu", "Kamryn Colman", "Kaho Funahashi", "Hope Maka", "Penny Starr", "Reya Adkins", "Erin Blackmore", "Ruby Nola", "Shyah Hale", "Loran Parker", "Alexia Lacatena", "Krysta Hoani", "Kurtis Tomkins", "Tania Parangi", "Tania Sampson"]},
]

// Top 50 career games per grade (NRC/AFC/NFS combined, as at end of 2025/26)
export const CAREER_MEN: CareerGames[] = [
  {"name": "Gerard Long", "games": 364},
  {"name": "Isaac Fletcher", "games": 357},
  {"name": "Nathan Nukunuku", "games": 321},
  {"name": "Ben Enoka", "games": 319},
  {"name": "Rueben Topia", "games": 317},
  {"name": "Joshua Kingi", "games": 294},
  {"name": "Thomas Enoka", "games": 285},
  {"name": "Alfons Oveinikovas", "games": 280},
  {"name": "Jerome Haretuku", "games": 268},
  {"name": "Callum Ryan", "games": 257},
  {"name": "Brad Rona", "games": 255},
  {"name": "Campbell Enoka", "games": 247},
  {"name": "Marty Cannons", "games": 245},
  {"name": "Kurtis Tomkins", "games": 237},
  {"name": "Taiki Apu", "games": 236},
  {"name": "Rhys Mau", "games": 234},
  {"name": "Aaron Thompson", "games": 232},
  {"name": "Josh Niu", "games": 232},
  {"name": "Paul Doolan", "games": 230},
  {"name": "Tony Niu", "games": 228},
  {"name": "Heinie Shannon", "games": 221},
  {"name": "Bernard Hale", "games": 215},
  {"name": "Michael Niu", "games": 214},
  {"name": "Connor Peden", "games": 210},
  {"name": "Zane Van Lieshout", "games": 205},
  {"name": "Rhys Evans", "games": 202},
  {"name": "Hayden Wildbore", "games": 198},
  {"name": "Corin Tauri", "games": 198},
  {"name": "Kallan Compain", "games": 197},
  {"name": "Nathan Thorp", "games": 194},
  {"name": "Nick McGregor", "games": 194},
  {"name": "Gordon Hooper", "games": 190},
  {"name": "John Hireme", "games": 187},
  {"name": "Duane Jerard", "games": 186},
  {"name": "Kirby Roper", "games": 184},
  {"name": "Mathew Oxley", "games": 184},
  {"name": "Bradley Bennett", "games": 183},
  {"name": "Dean Wallace", "games": 179},
  {"name": "Darryn Tapsell", "games": 177},
  {"name": "Greg Anderson", "games": 177},
  {"name": "Andrew McMillan", "games": 175},
  {"name": "Bayley Hoani", "games": 175},
  {"name": "Cole Evans", "games": 174},
  {"name": "Aaron Knight", "games": 173},
  {"name": "Max Maoate", "games": 173},
  {"name": "Luke Peters", "games": 172},
  {"name": "Andrew Van Stipriaan", "games": 170},
  {"name": "Simon McMillan", "games": 169},
  {"name": "Leon Lambert", "games": 168},
  {"name": "Maddix Rice", "games": 167},
]

export const CAREER_WOMEN: CareerGames[] = [
  {"name": "Rebecca Bromhead", "games": 378},
  {"name": "Kyla Bromhead", "games": 329},
  {"name": "Kayla Clark", "games": 310},
  {"name": "Krysta Hoani", "games": 296},
  {"name": "Breanna Russell", "games": 265},
  {"name": "Nita Hickey", "games": 253},
  {"name": "Ariana Kingi", "games": 247},
  {"name": "Carina Hale", "games": 237},
  {"name": "Katrina Nukunuku", "games": 230},
  {"name": "Tegan Bromhead", "games": 227},
  {"name": "Freya Bullock", "games": 225},
  {"name": "Michal Fletcher", "games": 223},
  {"name": "Gillian Wills", "games": 208},
  {"name": "Shonelle Wihapi", "games": 201},
  {"name": "Natasha Taylor", "games": 199},
  {"name": "Hollie Howard", "games": 198},
  {"name": "Victoria Reyland", "games": 193},
  {"name": "Loran Parker", "games": 193},
  {"name": "Zoe Tolhopf", "games": 191},
  {"name": "Sina Hunkin", "games": 180},
  {"name": "Beth Stavert", "games": 176},
  {"name": "Tyla Morrison", "games": 175},
  {"name": "Dominique Rangi", "games": 172},
  {"name": "Kirsty Lakay", "games": 172},
  {"name": "Casey Roper", "games": 171},
  {"name": "Jenny Williams", "games": 171},
  {"name": "Aroha Noanoa", "games": 170},
  {"name": "Tamzin Smith", "games": 161},
  {"name": "A'eesha Hooper", "games": 159},
  {"name": "Courtney Warren", "games": 158},
  {"name": "Tuhi Cooper", "games": 157},
  {"name": "Katie Smith", "games": 155},
  {"name": "Samantha Parks", "games": 153},
  {"name": "Katie Heatherington", "games": 152},
  {"name": "Tyneesha Houkamau", "games": 152},
  {"name": "Brooke Whiteman", "games": 149},
  {"name": "Taylor Maxwell", "games": 149},
  {"name": "Jennifer Feret Brear", "games": 147},
  {"name": "Aroha Haretuku", "games": 145},
  {"name": "Lisa Arkell", "games": 144},
  {"name": "Santana Hala", "games": 144},
  {"name": "Ashley Scott", "games": 143},
  {"name": "Courtney Walker", "games": 136},
  {"name": "Cheyenne Young", "games": 133},
  {"name": "Claudia Gibson", "games": 132},
  {"name": "Krystal Tourangi", "games": 132},
  {"name": "Taryn Barber", "games": 132},
  {"name": "Anita Leeuw", "games": 130},
  {"name": "Michelle Kingi", "games": 129},
  {"name": "Michelle Love", "games": 129},
]
