// NFS Premier League Honours — Premier Men & Premier Women awards, 2004-05 to 2025-26
// Source: NFS_AFC_HISTORY.xlsx (Awards tab). Update once per season.

export type SeasonAwards = {
  season: string
  men: Record<string, string | null>
  women: Record<string, string | null>
}

export const AWARD_LABELS: Record<string, string> = {
  top_batter: "Top Batter",
  top_pitcher: "Top Pitcher",
  most_rbi: "Most RBI's",
  most_hr: "Most Homeruns",
  most_sb: "Most Stolen Bases",
  best_fairest: "Best & Fairest",
  players_choice: "Players' Choice",
  nathan_nukunuku: "Nathan Nukunuku Award",
  rebecca_bromhead: "Rebecca Bromhead Award",
  mvp: "MVP",
}

// Award keys in display order (men use nathan_nukunuku, women use rebecca_bromhead)
export const MEN_AWARDS = ['mvp','top_batter','top_pitcher','most_rbi','most_hr','most_sb','best_fairest','players_choice','nathan_nukunuku'] as const
export const WOMEN_AWARDS = ['mvp','top_batter','top_pitcher','most_rbi','most_hr','most_sb','best_fairest','players_choice','rebecca_bromhead'] as const

export const HONOURS: SeasonAwards[] = [
  { season: "2004-05", men: {"top_batter": "Brad Rona", "top_pitcher": "Brad Rona", "most_rbi": "Jason Gerbes", "most_hr": null, "most_sb": null, "best_fairest": null, "players_choice": null, "nathan_nukunuku": null, "mvp": null}, women: {"top_batter": null, "top_pitcher": null, "most_rbi": null, "most_hr": null, "most_sb": null, "best_fairest": null, "players_choice": null, "rebecca_bromhead": null, "mvp": null} },
  { season: "2005-06", men: {"top_batter": "Patrick Shannon", "top_pitcher": "Steven Tau", "most_rbi": "Lyndon Andrew", "most_hr": "Lyndon Andrew", "most_sb": "Patrick Shannon", "best_fairest": null, "players_choice": null, "nathan_nukunuku": null, "mvp": "Patrick Shannon"}, women: {"top_batter": "Katie Hetherington", "top_pitcher": "Michelle Kingi", "most_rbi": "Katie Hetherington", "most_hr": "Helen Packer", "most_sb": "Fiona Timu", "best_fairest": "Michelle Kingi", "players_choice": "Ashley Johnston", "rebecca_bromhead": null, "mvp": "Fiona Timu"} },
  { season: "2006-07", men: {"top_batter": "Lyndon Andrew", "top_pitcher": "Heinie Shannon", "most_rbi": "Carlaus Te Kawa", "most_hr": "Nathan Nukunuku", "most_sb": "Jonathan Munden", "best_fairest": "Kim Hansen", "players_choice": "Ben Enoka", "nathan_nukunuku": null, "mvp": "Nathan Nukunuku"}, women: {"top_batter": "Sina Hunkin", "top_pitcher": "Michal Tangaroa", "most_rbi": "Megan Farrell", "most_hr": "Lisa Hau", "most_sb": "Tegan Bromhead & Ngamoko Hiku", "best_fairest": "Megan Farrell", "players_choice": "Michal Tangaroa", "rebecca_bromhead": null, "mvp": "Ngamoko Hiku"} },
  { season: "2007-08", men: {"top_batter": "Patrick Shannon", "top_pitcher": "Thomas Cameron", "most_rbi": "Scott O'Neale", "most_hr": null, "most_sb": "Nathan Nukunuku", "best_fairest": "Nathan Thorpe", "players_choice": "Ryan Croawell", "nathan_nukunuku": null, "mvp": "Heinie Shannon"}, women: {"top_batter": "Sheree Cartwright", "top_pitcher": "Sheree Cartwright", "most_rbi": "Sabrina Nihoj", "most_hr": "Sina Hunkin", "most_sb": "Shonelle Wihapi", "best_fairest": "Selena Hoani", "players_choice": "Kayla Clark", "rebecca_bromhead": null, "mvp": "Sheree Cartwright"} },
  { season: "2008-09", men: {"top_batter": "Thomas Enoka", "top_pitcher": "Brad Rona", "most_rbi": "Ben Enoka", "most_hr": "Kurt Allan", "most_sb": "Curtis Cosh", "best_fairest": "Sam Hiko", "players_choice": "Tony Niu", "nathan_nukunuku": null, "mvp": "Thomas Enoka"}, women: {"top_batter": "Sheree Cartwright", "top_pitcher": "Michal Tangaroa", "most_rbi": "Mereana Joseph", "most_hr": "Michelle Ramea", "most_sb": "Jenna Woepse", "best_fairest": "Kyla Bromhead", "players_choice": "Sally Bowden", "rebecca_bromhead": null, "mvp": "Michal Tangaroa"} },
  { season: "2009-10", men: {"top_batter": "Patrick Shannon", "top_pitcher": "Brad Rona", "most_rbi": "Michael Niu", "most_hr": "Michael Niu", "most_sb": "Nathan Nukunuku", "best_fairest": "Donny Hale", "players_choice": "Jerome Haretuku", "nathan_nukunuku": null, "mvp": "Brad Rona"}, women: {"top_batter": "Tuhi Cooper", "top_pitcher": "Michal Tangaroa", "most_rbi": "Victoria Reyland", "most_hr": "Michal Tangaroa", "most_sb": "Sina Hunkin", "best_fairest": "Heidi Leathart", "players_choice": "Anita Leeuw", "rebecca_bromhead": null, "mvp": "Kyla Bromhead"} },
  { season: "2010-11", men: {"top_batter": "Brad Rona", "top_pitcher": "Brad Rona", "most_rbi": "Jason Gerbes", "most_hr": "Duane Jerard", "most_sb": "Roman Gabriel", "best_fairest": "Aaron Thompson", "players_choice": "Mathew Hicks", "nathan_nukunuku": null, "mvp": "Brad Rona"}, women: {"top_batter": "Te Reo Powhiri Matautia", "top_pitcher": "Jennifer Feret", "most_rbi": "Clarissa Mafoe", "most_hr": "Rebecca Bromhead", "most_sb": "Kataraina Hiku", "best_fairest": "Jennifer Feret", "players_choice": "Jennifer Feret", "rebecca_bromhead": null, "mvp": "Jennifer Feret"} },
  { season: "2011-12", men: {"top_batter": "Brad Rona", "top_pitcher": "Thomas Enoka", "most_rbi": "Tony Niu", "most_hr": "Brad Rona", "most_sb": "Bernard Hale", "best_fairest": "Tamihana Nau", "players_choice": "Jerome Haretuku", "nathan_nukunuku": null, "mvp": "Brad Rona"}, women: {"top_batter": "Michal Tangaroa", "top_pitcher": "Michelle Kingi", "most_rbi": "Tuhi Cooper", "most_hr": "Santana Harris", "most_sb": "Jaimee-Ann Dick", "best_fairest": "Stephanie Utanga", "players_choice": "Santana Harris", "rebecca_bromhead": null, "mvp": "Michal Tangaroa"} },
  { season: "2012-13", men: {"top_batter": "Ben Enoka", "top_pitcher": "Thomas Enoka", "most_rbi": "Thomas Enoka", "most_hr": "Thomas Enoka", "most_sb": "Sam Brown", "best_fairest": "Jordan Thorpe", "players_choice": "Thomas Enoka", "nathan_nukunuku": null, "mvp": "Thomas Enoka"}, women: {"top_batter": "Kaleo Eldredge", "top_pitcher": "Michal Tangaroa", "most_rbi": "Kaleo Eldredge", "most_hr": "Victoria Reyland", "most_sb": "Jennifer Feret", "best_fairest": "Tyneesha Houkamau", "players_choice": "Tyneesha Houkamau", "rebecca_bromhead": null, "mvp": "Kaleo Eldredge"} },
  { season: "2013-14", men: {"top_batter": "Michael Niu", "top_pitcher": "Campbell Gibson", "most_rbi": "Thomas Enoka", "most_hr": "Thomas Enoka", "most_sb": "Sam Brown", "best_fairest": "Bayley Hoani", "players_choice": "Michael Niu", "nathan_nukunuku": null, "mvp": "Michael Niu"}, women: {"top_batter": "Kaleo Eldredge", "top_pitcher": "Samantha Parks", "most_rbi": "Beth Stavert", "most_hr": "Stefanie Trutanic", "most_sb": "Ancelle Van Molendorff", "best_fairest": "Carina Hale", "players_choice": "Pania Monk", "rebecca_bromhead": null, "mvp": "Beth Stavert"} },
  { season: "2014-15", men: {"top_batter": "Ben Enoka", "top_pitcher": "Heinie Shannon", "most_rbi": "John Hireme", "most_hr": "Ben Enoka", "most_sb": "Kirby Roper", "best_fairest": "Bayley Hoani", "players_choice": "Kirby Roper", "nathan_nukunuku": null, "mvp": "Ben Enoka"}, women: {"top_batter": "Kaleo Eldredge", "top_pitcher": "Blaire Luna", "most_rbi": "Jennifer Feret", "most_hr": "Mandy Ogle", "most_sb": "Jaimee-Ann Dick", "best_fairest": "Carina Hale", "players_choice": "Katrina Nukunuku", "rebecca_bromhead": null, "mvp": "Sammi Parks"} },
  { season: "2015-16", men: {"top_batter": "Cole Evans", "top_pitcher": "Thomas Enoka", "most_rbi": "Lewis Jerard", "most_hr": "Jerome Haretuku", "most_sb": "Stuart Reynolds", "best_fairest": "Kurtis Tomkins", "players_choice": "Joshua Kingi", "nathan_nukunuku": null, "mvp": "Ben Enoka"}, women: {"top_batter": "Kaleo Eldredge", "top_pitcher": "Jennifer Feret", "most_rbi": "Kaleo Eldredge", "most_hr": "Rachel Van Veen", "most_sb": "Stefanie Smith", "best_fairest": "Breanna Gibson", "players_choice": "Ariana Kingi", "rebecca_bromhead": null, "mvp": "Jennifer Feret"} },
  { season: "2016-17", men: {"top_batter": "Thomas Enoka", "top_pitcher": "Bayley Hoani", "most_rbi": "Campbell Enoka", "most_hr": "Campbell Enoka", "most_sb": "David-Lee Alexander", "best_fairest": "Rhys Evans", "players_choice": "Ryan Kennedy", "nathan_nukunuku": null, "mvp": "Campbell Enoka"}, women: {"top_batter": "Aaria Tawha", "top_pitcher": "Jamie Allred", "most_rbi": "Krysta Hoani", "most_hr": "Tomoka Goda", "most_sb": "Nita Hickey", "best_fairest": "Kelsey Rangi", "players_choice": "Tyla Morrison", "rebecca_bromhead": null, "mvp": "Katrina Nukunuku"} },
  { season: "2017-18", men: {"top_batter": "Brad Rona", "top_pitcher": "Pita Rona", "most_rbi": "Cole Evans", "most_hr": "Cole Evans", "most_sb": "Leon Graham", "best_fairest": "Rhys Mau", "players_choice": "Huw Davies", "nathan_nukunuku": null, "mvp": "Campbell Gibson"}, women: {"top_batter": "Kaleo Eldredge", "top_pitcher": "Samantha Parks", "most_rbi": "Lisa Maulden", "most_hr": "Lisa Maulden", "most_sb": "Kingsley Avery", "best_fairest": "Rachel Young", "players_choice": "Katrina Nukunuku", "rebecca_bromhead": null, "mvp": "Kyla Bromhead"} },
  { season: "2018-19", men: {"top_batter": "Cole Evans", "top_pitcher": "Campbell Gibson", "most_rbi": "Cole Evans", "most_hr": "Cole Evans", "most_sb": "Thomas Enoka", "best_fairest": "Andy McMillan", "players_choice": "Campbell Gibson", "nathan_nukunuku": null, "mvp": "Cole Evans"}, women: {"top_batter": "Cheyanne Tarango", "top_pitcher": "Cheyanne Tarango", "most_rbi": "Cheyanne Tarango", "most_hr": "Stephanie Texeira", "most_sb": "Gretchen Aucoin", "best_fairest": "Michelle Kingi", "players_choice": "Pearl-Marli Waetford", "rebecca_bromhead": null, "mvp": "Gretchen Aucoin"} },
  { season: "2019-20", men: {"top_batter": "Thomas Enoka", "top_pitcher": "Bayley Pearson-Hoani", "most_rbi": "Kallan Compain", "most_hr": "Connor Peden", "most_sb": "Pita Rona", "best_fairest": null, "players_choice": "Seth Gibson", "nathan_nukunuku": null, "mvp": "Kallan Compain"}, women: {"top_batter": "Logan Moreland", "top_pitcher": "Gretchen Aucoin", "most_rbi": "Stephanie Texeira", "most_hr": "Stephanie Texeira", "most_sb": "Tenille Auimatagi", "best_fairest": null, "players_choice": "Lily Nielsen", "rebecca_bromhead": null, "mvp": "Stephanie Texeira"} },
  { season: "2020-21", men: {"top_batter": "Alfons Oveinikovas", "top_pitcher": "Daniel Chapman", "most_rbi": "Jerome Haretuku", "most_hr": "Alfons Oveinikovas", "most_sb": "Te Kirika Cooper-Nicola", "best_fairest": null, "players_choice": null, "nathan_nukunuku": "Max Earley", "mvp": "Alfons Oveinikovas"}, women: {"top_batter": "Tara Jeffery", "top_pitcher": "Loran Parker", "most_rbi": "Rebecca Bromhead", "most_hr": "Gretchen Aucoin", "most_sb": "Logan Moreland", "best_fairest": null, "players_choice": null, "rebecca_bromhead": "Pania Monk", "mvp": "Logan Moreland"} },
  { season: "2021-22", men: {"top_batter": null, "top_pitcher": null, "most_rbi": null, "most_hr": null, "most_sb": null, "best_fairest": null, "players_choice": null, "nathan_nukunuku": null, "mvp": null}, women: {"top_batter": "Krysta Hoani", "top_pitcher": "Loran Parker", "most_rbi": "Shyah Hale", "most_hr": "Shyah Hale", "most_sb": "Brooke Whiteman", "best_fairest": null, "players_choice": null, "rebecca_bromhead": "Shyah Hale", "mvp": "Shyah Hale"} },
  { season: "2022-23", men: {"top_batter": "Tim Kelly", "top_pitcher": "Taine Slaughter", "most_rbi": "Tim Kelly", "most_hr": "Connor Peden", "most_sb": "Logan Esau", "best_fairest": null, "players_choice": null, "nathan_nukunuku": "Rhys Evans", "mvp": "Connor Peden"}, women: {"top_batter": "Cassady Knudsen", "top_pitcher": "Loran Parker", "most_rbi": "Stephanie Texeira", "most_hr": "Logan Moreland", "most_sb": "Katrina Nukunuku", "best_fairest": null, "players_choice": null, "rebecca_bromhead": "Cassady Knudsen", "mvp": "Logan Moreland"} },
  { season: "2023-24", men: {"top_batter": "Matthew Oxley", "top_pitcher": "Dallas Amai Tatu", "most_rbi": "Floyd Nola", "most_hr": "Oscar Clark", "most_sb": "Blake Wardrope", "best_fairest": null, "players_choice": null, "nathan_nukunuku": "Floyd Nola", "mvp": "Floyd Nola"}, women: {"top_batter": "Kamryn Coleman", "top_pitcher": "Cassady Knudsen", "most_rbi": "Kamryn Coleman", "most_hr": "Shyah Hale", "most_sb": "Freya Bullock", "best_fairest": null, "players_choice": null, "rebecca_bromhead": "Loran Parker", "mvp": "Shyah Hale"} },
  { season: "2024-25", men: {"top_batter": "Cole Evans", "top_pitcher": "Taine Slaughter", "most_rbi": "Cole Evans", "most_hr": "Cole Evans", "most_sb": "Oscar Clark", "best_fairest": null, "players_choice": null, "nathan_nukunuku": "Ihaka Tangaroa", "mvp": "Cole Evans"}, women: {"top_batter": "Alyx Bloom", "top_pitcher": "Charlotte Graham", "most_rbi": "Chloe Malau'ulu", "most_hr": "Chloe Malau'ulu", "most_sb": "Jessie Jackson", "best_fairest": null, "players_choice": null, "rebecca_bromhead": "Kamryn Coleman", "mvp": "Kamryn Coleman"} },
  { season: "2025-26", men: {"top_batter": "Thomas Enoka", "top_pitcher": "Liam Twigden", "most_rbi": "Thomas Enoka", "most_hr": "Thomas Enoka", "most_sb": "Harrison Wildbore", "best_fairest": null, "players_choice": null, "nathan_nukunuku": "Traye Wildbore", "mvp": "Thomas Enoka"}, women: {"top_batter": "Kamryn Coleman", "top_pitcher": "Lauren Heinsdijk", "most_rbi": "Shyah Hale", "most_hr": "Shyah Hale", "most_sb": "Penny Starr", "best_fairest": null, "players_choice": null, "rebecca_bromhead": "Shyah Hale", "mvp": "Shyah Hale"} },
]