// NFS milestones and challenge shields — generated from NFS_AFC_HISTORY.xlsx
// Career game figures are a snapshot as at season ending 2025/26.

export type Milestone = { name: string; club: string; games: number; tier: 100 | 200 | 300; season: string; grade: 'men' | 'women' }
export type ShieldEvent = { shield: string; holder: string; result: 'Held' | 'Lost'; date: string; challenger: string }

export const MILESTONES: Milestone[] = [
  { name: 'Gerard Long', club: 'Waitakere Bears', games: 100, tier: 100, season: '2008-09', grade: 'men' },
  { name: 'Jerome Haretuku', club: 'Marist', games: 100, tier: 100, season: '2008-09', grade: 'men' },
  { name: 'Callum Ryan', club: 'Northcote', games: 119, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Nathan Nukunuku', club: 'Ramblers', games: 117, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Laurie Katene', club: 'Otahuhu', games: 116, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Leon Lambert', club: 'Northcote', games: 116, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Aaron Thompson', club: 'Ramblers', games: 115, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Ben Enoka', club: 'United', games: 114, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Jamie Love', club: 'Marist', games: 114, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Tony Niu', club: 'United', games: 113, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Corin Tauri', club: 'Glenora', games: 112, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Dean Wallace', club: 'Northcote', games: 112, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Isaac Fletcher', club: 'Waitakere Bears', games: 112, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Duane Jerard', club: 'Eden Roskill', games: 111, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Gordon Hooper', club: 'Eden Roskill', games: 111, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Josh Niu', club: 'Eden Roskill', games: 111, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Bernard Hale', club: 'Ramblers', games: 110, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Joshua Kingi', club: 'Howick', games: 110, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Lawrence Naera', club: 'Ramblers', games: 110, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Casey Eden', club: 'Waitakere Bears', games: 109, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Brad Rona', club: 'Northcote', games: 107, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Reece Gasson', club: 'United', games: 107, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'John Hireme', club: 'Ramblers', games: 106, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Lyndon Andrew', club: 'Marist', games: 106, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Paul Doolan', club: 'Eden Roskill', games: 106, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Heinie Shannon', club: 'Waitakere Bears', games: 105, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Michael Gibbs', club: 'Ramblers', games: 105, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Michael Niu', club: 'United', games: 105, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Taiki Apu', club: 'Eden Roskill', games: 105, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Hayden Wildbore', club: 'Howick', games: 104, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Rhys Mau', club: 'Howick', games: 104, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Rueben Topia', club: 'Waitakere Bears', games: 104, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Dylan Tomlin', club: 'Marist', games: 103, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Patrick Shannon', club: 'Waitakere Bears', games: 101, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Michael Cameron', club: 'Ramblers', games: 100, tier: 100, season: '2009-10', grade: 'men' },
  { name: 'Roman Gabriel', club: 'Marist', games: 100, tier: 100, season: '2010-11', grade: 'men' },
  { name: 'Troy Pirie', club: 'Howick', games: 100, tier: 100, season: '2010-11', grade: 'men' },
  { name: 'Nick McGregor', club: 'United', games: 115, tier: 100, season: '2011-12', grade: 'men' },
  { name: 'Kurt Allan', club: 'United', games: 110, tier: 100, season: '2011-12', grade: 'men' },
  { name: 'Kirby Roper', club: 'Eden Roskill', games: 110, tier: 100, season: '2011-12', grade: 'men' },
  { name: 'Alfons Oveinikovas', club: 'Waitakere Bears', games: 110, tier: 100, season: '2011-12', grade: 'men' },
  { name: 'Bobbie King', club: 'Ramblers', games: 109, tier: 100, season: '2011-12', grade: 'men' },
  { name: 'Thomas Enoka', club: 'United', games: 114, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Josh Cooke', club: 'United', games: 112, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Marty Cannons', club: 'Marist', games: 112, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Nathan Thorp', club: 'Eden Roskill', games: 109, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Steffan van Lieshout', club: 'Eden Roskill', games: 108, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'James Moses', club: 'Waitakere Bears', games: 107, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Darryn Tapsell', club: 'Roosters', games: 107, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'David MacKenzie', club: 'Marist', games: 105, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Brock Williams', club: 'United', games: 104, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Jordan Thorp', club: 'Eden Roskill', games: 100, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Max Maoate', club: 'Eden Roskill', games: 100, tier: 100, season: '2012-13', grade: 'men' },
  { name: 'Kurtis Tomkins', club: 'Roosters', games: 119, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Zane Van Lieshout', club: 'Eden Roskill', games: 117, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Aaron Knight', club: 'Roosters', games: 113, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Greg Anderson', club: 'Ramblers', games: 113, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Donny Hale', club: 'Ramblers', games: 104, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Curtis Cosh', club: 'Eden Roskill', games: 103, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Bayley Hoani', club: 'United', games: 103, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Lee Rudolph', club: 'Northcote', games: 102, tier: 100, season: '2013-14', grade: 'men' },
  { name: 'Yoshi Suzuki', club: 'Howick', games: 107, tier: 100, season: '2014-15', grade: 'men' },
  { name: 'Kallan Compain', club: 'United', games: 106, tier: 100, season: '2014-15', grade: 'men' },
  { name: 'Campbell Enoka', club: 'United', games: 103, tier: 100, season: '2014-15', grade: 'men' },
  { name: 'Regan O\'Neil', club: 'Howick', games: 100, tier: 100, season: '2014-15', grade: 'men' },
  { name: 'Mathew Oxley', club: 'Marist', games: 112, tier: 100, season: '2015-16', grade: 'men' },
  { name: 'Tamihana Nau', club: 'United', games: 108, tier: 100, season: '2015-16', grade: 'men' },
  { name: 'Garth Pollard', club: 'United', games: 102, tier: 100, season: '2015-16', grade: 'men' },
  { name: 'Taylor Hick', club: 'Waitakere Bears', games: 100, tier: 100, season: '2015-16', grade: 'men' },
  { name: 'Chase Rouse', club: 'Otahuhu', games: 115, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Ben Bull', club: 'Marist', games: 114, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Andrew McMillan', club: 'Eden Roskill', games: 109, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Luke Peters', club: 'Marist', games: 108, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Andrew Van Stipriaan', club: 'Roosters', games: 106, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Kevy Cannons', club: 'Roosters', games: 104, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Connor Peden', club: 'Ramblers', games: 102, tier: 100, season: '2016-17', grade: 'men' },
  { name: 'Kere Hauraki', club: 'Otahuhu', games: 114, tier: 100, season: '2017-18', grade: 'men' },
  { name: 'Campbell Gibson', club: 'Howick', games: 113, tier: 100, season: '2017-18', grade: 'men' },
  { name: 'Bradley Bennett', club: 'Ramblers', games: 112, tier: 100, season: '2017-18', grade: 'men' },
  { name: 'Pita Rona', club: 'Northcote', games: 108, tier: 100, season: '2017-18', grade: 'men' },
  { name: 'Rhys Evans', club: 'Ramblers', games: 107, tier: 100, season: '2017-18', grade: 'men' },
  { name: 'Mark Sorenson', club: 'United', games: 103, tier: 100, season: '2017-18', grade: 'men' },
  { name: 'Jared Hauraki', club: 'Otahuhu', games: 114, tier: 100, season: '2018-19', grade: 'men' },
  { name: 'Cole Evans', club: 'Ramblers', games: 109, tier: 100, season: '2018-19', grade: 'men' },
  { name: 'Stuart Reynolds', club: 'Howick', games: 109, tier: 100, season: '2018-19', grade: 'men' },
  { name: 'Hohepa Monk', club: 'Northcote', games: 108, tier: 100, season: '2018-19', grade: 'men' },
  { name: 'Ryan Kennedy', club: 'Roosters', games: 106, tier: 100, season: '2018-19', grade: 'men' },
  { name: 'David Lee Alexander', club: 'Marist', games: 104, tier: 100, season: '2018-19', grade: 'men' },
  { name: 'Hannon Hoani', club: 'Otahuhu', games: 113, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Cory Collins', club: 'Roosters', games: 112, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Jacob Oxley', club: 'Marist', games: 109, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Lewis Jerard', club: 'Ramblers', games: 107, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Vikita Ale', club: 'Otahuhu', games: 107, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Simon McMillan', club: 'United', games: 106, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Travis Hauraki', club: 'Otahuhu', games: 106, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Cayne Mihaere', club: 'Roosters', games: 105, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Joseph Hall', club: 'Roosters', games: 104, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Eruera Drage', club: 'Roosters', games: 102, tier: 100, season: '2019-20', grade: 'men' },
  { name: 'Maddix Rice', club: 'Ramblers', games: 110, tier: 100, season: '2020-21', grade: 'men' },
  { name: 'Kaleb Rona', club: 'United', games: 109, tier: 100, season: '2020-21', grade: 'men' },
  { name: 'Brock Attewell', club: 'United', games: 106, tier: 100, season: '2020-21', grade: 'men' },
  { name: 'Blake Radford', club: 'Roosters', games: 105, tier: 100, season: '2020-21', grade: 'men' },
  { name: 'Cameron Johnson', club: 'Howick', games: 102, tier: 100, season: '2020-21', grade: 'men' },
  { name: 'Jordan Tahana', club: 'Howick', games: 107, tier: 100, season: '2022-23', grade: 'men' },
  { name: 'Huw Davies', club: 'Howick', games: 104, tier: 100, season: '2022-23', grade: 'men' },
  { name: 'Logan Esau', club: 'Marist', games: 112, tier: 100, season: '2023-24', grade: 'men' },
  { name: 'Liam Twigden', club: 'United', games: 105, tier: 100, season: '2023-24', grade: 'men' },
  { name: 'Aaron Dormer', club: 'Marist', games: 104, tier: 100, season: '2024-25', grade: 'men' },
  { name: 'Floyd Nola', club: 'Ramblers', games: 102, tier: 100, season: '2025-26', grade: 'men' },
  { name: 'Seth Bourgeois', club: 'Ramblers', games: 102, tier: 100, season: '2025-26', grade: 'men' },
  { name: 'Brock Evans', club: 'Ramblers', games: 101, tier: 100, season: '2025-26', grade: 'men' },
  { name: 'Harrison Wildbore', club: 'Howick', games: 101, tier: 100, season: '2025-26', grade: 'men' },
  { name: 'Gerard Long', club: '', games: 217, tier: 200, season: '2014-15', grade: 'men' },
  { name: 'Aaron Thompson', club: 'Ramblers', games: 215, tier: 200, season: '2014-15', grade: 'men' },
  { name: 'Isaac Fletcher', club: 'United', games: 204, tier: 200, season: '2014-15', grade: 'men' },
  { name: 'Nathan Nukunuku', club: 'Ramblers', games: 203, tier: 200, season: '2014-15', grade: 'men' },
  { name: 'Tony Niu', club: 'Roosters', games: 202, tier: 200, season: '2014-15', grade: 'men' },
  { name: 'Rueben Topia', club: 'United', games: 214, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Josh Niu', club: 'Waitakere Bears', games: 213, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Callum Ryan', club: 'Northcote', games: 211, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Brad Rona', club: 'Northcote', games: 208, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Bernard Hale', club: 'Marist', games: 201, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Ben Enoka', club: 'United', games: 201, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Joshua Kingi', club: 'Eden Roskill', games: 200, tier: 200, season: '2015-16', grade: 'men' },
  { name: 'Jerome Haretuku', club: 'Marist', games: 214, tier: 200, season: '2016-17', grade: 'men' },
  { name: 'Taiki Apu', club: 'Eden Roskill', games: 210, tier: 200, season: '2016-17', grade: 'men' },
  { name: 'Paul Doolan', club: 'Eden Roskill', games: 206, tier: 200, season: '2016-17', grade: 'men' },
  { name: 'Rhys Mau', club: 'Otahuhu', games: 215, tier: 200, season: '2017-18', grade: 'men' },
  { name: 'Michael Niu', club: 'Waitakere Bears', games: 212, tier: 200, season: '2017-18', grade: 'men' },
  { name: 'Alfons Oveinikovas', club: 'United', games: 211, tier: 200, season: '2017-18', grade: 'men' },
  { name: 'Heinie Shannon', club: 'Marist', games: 205, tier: 200, season: '2017-18', grade: 'men' },
  { name: 'Thomas Enoka', club: 'United', games: 214, tier: 200, season: '2018-19', grade: 'men' },
  { name: 'Marty Cannons', club: 'Roosters', games: 214, tier: 200, season: '2018-19', grade: 'men' },
  { name: 'Kurtis Tomkins', club: 'Roosters', games: 203, tier: 200, season: '2018-19', grade: 'men' },
  { name: 'Zane Van Lieshout', club: 'Ramblers', games: 205, tier: 200, season: '2019-20', grade: 'men' },
  { name: 'Campbell Enoka', club: 'United', games: 202, tier: 200, season: '2021-22', grade: 'men' },
  { name: 'Connor Peden', club: 'Ramblers', games: 203, tier: 200, season: '2024-25', grade: 'men' },
  { name: 'Rhys Evans', club: 'Ramblers', games: 202, tier: 200, season: '2025-26', grade: 'men' },
  { name: 'Gerard Long', club: 'Marist', games: 302, tier: 300, season: '2019-20', grade: 'men' },
  { name: 'Isaac Fletcher', club: 'United', games: 306, tier: 300, season: '2022-23', grade: 'men' },
  { name: 'Rueben Topia', club: 'United', games: 302, tier: 300, season: '2022-23', grade: 'men' },
  { name: 'Nathan Nukunuku', club: 'Ramblers', games: 307, tier: 300, season: '2023-24', grade: 'men' },
  { name: 'Ben Enoka', club: 'United', games: 300, tier: 300, season: '2024-25', grade: 'men' },
  { name: 'Rebecca Bromhead', club: 'Waitakere Bears', games: 107, tier: 100, season: '2009-10', grade: 'women' },
  { name: 'Casey Roper', club: 'Otahuhu', games: 103, tier: 100, season: '2009-10', grade: 'women' },
  { name: 'Tegan Bromhead', club: 'Waitakere Bears', games: 102, tier: 100, season: '2009-10', grade: 'women' },
  { name: 'Kayla Clark', club: 'Waitakere Bears', games: 115, tier: 100, season: '2010-11', grade: 'women' },
  { name: 'Mereana Joseph', club: 'Waitakere Bears', games: 112, tier: 100, season: '2010-11', grade: 'women' },
  { name: 'Lisa Arkell', club: 'Otahuhu', games: 108, tier: 100, season: '2010-11', grade: 'women' },
  { name: 'Kyla Bromhead', club: 'Waitakere Bears', games: 103, tier: 100, season: '2010-11', grade: 'women' },
  { name: 'Victoria Reyland', club: 'Ramblers', games: 100, tier: 100, season: '2010-11', grade: 'women' },
  { name: 'Dominique Rangi', club: 'Metro', games: 115, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Breanna Russell (Nee Gibson)', club: 'Howick', games: 112, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Tuhi Cooper', club: 'Ramblers', games: 111, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Michelle Kingi', club: 'Papatoetoe', games: 108, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Michal Fletcher (Nee Tangaroa)', club: 'Waitakere Bears', games: 107, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Courtney Warren', club: 'Otahuhu', games: 107, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Katie Heatherington', club: 'Papatoetoe', games: 105, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Alorna Ngatokurua', club: 'Otahuhu', games: 104, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Megan Farrell', club: 'Ramblers', games: 102, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Shonelle Wihapi', club: 'Waitakere Bears', games: 101, tier: 100, season: '2011-12', grade: 'women' },
  { name: 'Aroha Haretuku', club: 'Papatoetoe', games: 112, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Jordan Wilson', club: 'Howick', games: 110, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Stephanie Utanga', club: 'Otahuhu', games: 107, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Michelle Love (Nee Smith)', club: 'Howick', games: 103, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Amanda Preston', club: 'Papatoetoe', games: 101, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Krysta Hoani', club: 'Otahuhu', games: 101, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Krystal Tourangi', club: 'Otahuhu', games: 101, tier: 100, season: '2012-13', grade: 'women' },
  { name: 'Gillian Wills', club: 'Magpies', games: 120, tier: 100, season: '2013-14', grade: 'women' },
  { name: 'Ariana Kingi', club: 'Howick', games: 111, tier: 100, season: '2013-14', grade: 'women' },
  { name: 'Nita Hickey', club: 'Otahuhu', games: 109, tier: 100, season: '2013-14', grade: 'women' },
  { name: 'Taryn Barber', club: 'Howick', games: 108, tier: 100, season: '2013-14', grade: 'women' },
  { name: 'Sina Hunkin', club: 'Magpies', games: 104, tier: 100, season: '2013-14', grade: 'women' },
  { name: 'Beth Stavert', club: 'Magpies', games: 115, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Anita Leeuw', club: 'Howick', games: 111, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Jenny Williams', club: 'Magpies', games: 110, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Kelly Browne', club: 'Waitakere Bears', games: 110, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Santana Hala (Nee Harris)', club: 'Otahuhu', games: 108, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Kayla Roundtree', club: 'Magpies', games: 107, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Freya Bullock', club: 'Ramblers', games: 105, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Ngawai Hira', club: 'Otahuhu', games: 103, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Natasha Taylor', club: 'Howick', games: 100, tier: 100, season: '2014-15', grade: 'women' },
  { name: 'Katie Smith', club: 'Ramblers', games: 116, tier: 100, season: '2015-16', grade: 'women' },
  { name: 'Courtney Walker', club: 'Waitakere Bears', games: 110, tier: 100, season: '2015-16', grade: 'women' },
  { name: 'Carina Hale', club: 'Waitakere Bears', games: 107, tier: 100, season: '2015-16', grade: 'women' },
  { name: 'Jennifer Feret Brear', club: 'Magpies', games: 105, tier: 100, season: '2015-16', grade: 'women' },
  { name: 'Georgia Rudd', club: 'Marist', games: 105, tier: 100, season: '2015-16', grade: 'women' },
  { name: 'Ancelle Van Molendorff', club: 'Waitakere Bears', games: 105, tier: 100, season: '2015-16', grade: 'women' },
  { name: 'Katrina Nukunuku', club: 'Ramblers', games: 110, tier: 100, season: '2016-17', grade: 'women' },
  { name: 'Kirsty Lakay', club: 'Marist', games: 109, tier: 100, season: '2016-17', grade: 'women' },
  { name: 'Samantha Parks', club: 'Otahuhu', games: 108, tier: 100, season: '2016-17', grade: 'women' },
  { name: 'Lisa Roberts', club: 'Roosters', games: 107, tier: 100, season: '2016-17', grade: 'women' },
  { name: 'Zoe Tolhopf', club: 'Howick', games: 121, tier: 100, season: '2017-18', grade: 'women' },
  { name: 'Kelsey Rangi', club: 'Otahuhu', games: 119, tier: 100, season: '2017-18', grade: 'women' },
  { name: 'A\'eesha Hooper', club: 'Waitakere Bears', games: 112, tier: 100, season: '2017-18', grade: 'women' },
  { name: 'Kaleo Eldredge', club: 'Magpies', games: 100, tier: 100, season: '2017-18', grade: 'women' },
  { name: 'Rachel Young', club: 'Glenfield', games: 100, tier: 100, season: '2017-18', grade: 'women' },
  { name: 'Marissa Berkes', club: 'Howick', games: 100, tier: 100, season: '2017-18', grade: 'women' },
  { name: 'Ashley Scott', club: 'Magpies', games: 117, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Tamzin Smith', club: 'Howick', games: 115, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Tyla Morrison', club: 'Waitakere Bears', games: 113, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Alison Mohi', club: 'Otahuhu', games: 112, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Kalala Gabriel', club: 'Marist', games: 110, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Sarah Wallace', club: 'Marist', games: 107, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Hollie Howard', club: 'Marist', games: 102, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Makayla Samaeli', club: 'Marist', games: 101, tier: 100, season: '2018-19', grade: 'women' },
  { name: 'Loran Parker', club: 'Otahuhu', games: 110, tier: 100, season: '2019-20', grade: 'women' },
  { name: 'Aroha Noanoa', club: 'Waitakere Bears', games: 101, tier: 100, season: '2019-20', grade: 'women' },
  { name: 'Brooke Whiteman', club: 'Ramblers', games: 112, tier: 100, season: '2020-21', grade: 'women' },
  { name: 'Rebecca Fox', club: 'Ramblers', games: 106, tier: 100, season: '2020-21', grade: 'women' },
  { name: 'Tenille Auimatagi', club: 'Waitakere Bears', games: 105, tier: 100, season: '2020-21', grade: 'women' },
  { name: 'Tyneesha Houkamau', club: 'Otahuhu', games: 102, tier: 100, season: '2020-21', grade: 'women' },
  { name: 'Claudia Gibson', club: 'Howick', games: 108, tier: 100, season: '2021-22', grade: 'women' },
  { name: 'Hayley Carter', club: 'Marist', games: 107, tier: 100, season: '2021-22', grade: 'women' },
  { name: 'Stefanie Smith', club: 'Howick', games: 101, tier: 100, season: '2021-22', grade: 'women' },
  { name: 'Taylor Maxwell', club: 'Waitakere Bears', games: 101, tier: 100, season: '2021-22', grade: 'women' },
  { name: 'Tatiana Rouru', club: 'Marist', games: 107, tier: 100, season: '2022-23', grade: 'women' },
  { name: 'Phoebe Davies', club: 'Metro', games: 107, tier: 100, season: '2022-23', grade: 'women' },
  { name: 'Vivian Marr', club: 'Bandits', games: 106, tier: 100, season: '2022-23', grade: 'women' },
  { name: 'Ashleigh Foley', club: 'Marist', games: 104, tier: 100, season: '2022-23', grade: 'women' },
  { name: 'Erena Sawada', club: 'Bandits', games: 106, tier: 100, season: '2023-24', grade: 'women' },
  { name: 'Pania Monk', club: 'AU Marist', games: 103, tier: 100, season: '2023-24', grade: 'women' },
  { name: 'Cheyenne Young', club: 'Bandits', games: 117, tier: 100, season: '2024-25', grade: 'women' },
  { name: 'Jordyn Murray', club: 'Roosters', games: 106, tier: 100, season: '2024-25', grade: 'women' },
  { name: 'Kaiah Lee O\'Brien', club: 'Otahuhu', games: 106, tier: 100, season: '2024-25', grade: 'women' },
  { name: 'Beth Reid', club: 'Ramblers', games: 101, tier: 100, season: '2024-25', grade: 'women' },
  { name: 'Taylor Chong', club: 'Otahuhu', games: 111, tier: 100, season: '2025-26', grade: 'women' },
  { name: 'Tyarn Bromhead Lemalu', club: 'Roosters', games: 110, tier: 100, season: '2025-26', grade: 'women' },
  { name: 'Jacqueline Clay', club: 'Patriots', games: 110, tier: 100, season: '2025-26', grade: 'women' },
  { name: 'Lily Neilson', club: 'Patriots', games: 107, tier: 100, season: '2025-26', grade: 'women' },
  { name: 'Lyric Wilson', club: 'Ramblers', games: 104, tier: 100, season: '2025-26', grade: 'women' },
  { name: 'Alyssa Bailey', club: 'Patriots', games: 102, tier: 100, season: '2025-26', grade: 'women' },
  { name: 'Rebecca Bromhead', club: 'Waitakere Bears', games: 208, tier: 200, season: '2015-16', grade: 'women' },
  { name: 'Kayla Clark', club: 'Waitakere Bears', games: 207, tier: 200, season: '2015-16', grade: 'women' },
  { name: 'Breanna Russell', club: 'Howick', games: 207, tier: 200, season: '2016-17', grade: 'women' },
  { name: 'Kyla Bromhead', club: 'Waitakere Bears', games: 219, tier: 200, season: '2017-18', grade: 'women' },
  { name: 'Tegan Bromhead', club: 'Waitakere Bears', games: 211, tier: 200, season: '2017-18', grade: 'women' },
  { name: 'Shonelle Wihapi', club: 'Ramblers', games: 201, tier: 200, season: '2017-18', grade: 'women' },
  { name: 'Gillian Wills', club: 'Magpies', games: 200, tier: 200, season: '2017-18', grade: 'women' },
  { name: 'Nita Hickey', club: 'Otahuhu', games: 210, tier: 200, season: '2018-19', grade: 'women' },
  { name: 'Krysta Hoani', club: 'Otahuhu', games: 203, tier: 200, season: '2018-19', grade: 'women' },
  { name: 'Ariana Kingi', club: 'Otahuhu', games: 209, tier: 200, season: '2019-20', grade: 'women' },
  { name: 'Michal Fletcher', club: 'Waitakere Bears', games: 203, tier: 200, season: '2019-20', grade: 'women' },
  { name: 'Freya Bullock', club: 'Metro', games: 217, tier: 200, season: '2023-24', grade: 'women' },
  { name: 'Katrina Nukunuku', club: 'Ramblers', games: 212, tier: 200, season: '2023-24', grade: 'women' },
  { name: 'Carina Hale', club: 'Waitakere Bears', games: 210, tier: 200, season: '2023-24', grade: 'women' },
  { name: 'Rebecca Bromhead', club: 'Waitakere Bears', games: 310, tier: 300, season: '2021-22', grade: 'women' },
  { name: 'Kayla Clark', club: 'Waitakere Bears', games: 302, tier: 300, season: '2022-23', grade: 'women' },
  { name: 'Kyla Bromhead', club: 'Waitakere Bears', games: 312, tier: 300, season: '2024-25', grade: 'women' },
]

export const SHIELD_EVENTS: ShieldEvent[] = [
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '31 October 2015', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '31 October 2015', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '12 December 2015', challenger: 'Otahuhu' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '16 January 2016', challenger: 'Ramblers' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Lost', date: '14 February 2016', challenger: 'Northcote' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Held', date: '1 October 2016', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Held', date: '16 October 2016', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Held', date: '', challenger: 'Otahuhu' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Held', date: '5 November 2016', challenger: 'Eden Roskill' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Lost', date: '8 December 2016', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '17 December 2016', challenger: 'Eden Roskill' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '14 January 2017', challenger: 'Otahuhu' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '21 February 2017', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '23 February 2017', challenger: 'Waitakere Bears' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '30 September 2017', challenger: 'Waitakere Bears' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '7 October 2017', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Lost', date: '10 October 2017', challenger: 'Northcote' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Held', date: '4 November 2017', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Held', date: '13 January 2018', challenger: 'Waitakere Bears' },
  { shield: 'Trevor Rouse Shield', holder: 'Northcote', result: 'Lost', date: '24 February 2018', challenger: 'Ramblers' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '4 March 2018', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '29 September 2018', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '3 November 2018', challenger: 'Otahuhu' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '4 November 2018', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '11 November 2018', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '11 November 2018', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '15 December 2018', challenger: 'Northcote' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '22 December 2018', challenger: 'Otahuhu' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '12 January 2019', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '23 February 2019', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '28 September 2019', challenger: 'Otahuhu' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '19 October 2019', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '2 November 2019', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '23 November 2019', challenger: 'Waitakere Bears' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '25 February 2020', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '31 October 2020', challenger: 'Waitakere Bears' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '7 November 2020', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '21 November 2020', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '4 December 2020', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '5 December 2020', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '23 January 2021', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '15 January 2022', challenger: 'Roosters' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '16 January 2022', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '8 October 2022', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '14 January 2023', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '11 February 2023', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '4 November 2023', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers Maroon', result: 'Lost', date: '4 October 2024', challenger: 'Ramblers Gold' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers Gold', result: 'Lost', date: '5 December 2024', challenger: 'Ramblers Maroon' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers Maroon', result: 'Held', date: '18 January 2025', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers Maroon', result: 'Held', date: '2 February 2025', challenger: 'Southern Pioneers' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers Maroon', result: 'Held', date: '', challenger: 'Pukekohe' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers Maroon', result: 'Lost', date: '13 February 2025', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Lost', date: '18 October 2025', challenger: 'Ramblers' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '1 November 2025', challenger: 'Pukekohe' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Held', date: '15 November 2025', challenger: 'Marist' },
  { shield: 'Trevor Rouse Shield', holder: 'Ramblers', result: 'Lost', date: '6 December 2025', challenger: 'Auckland United' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '31 January 2026', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '10 February 2026', challenger: 'Howick' },
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', result: 'Held', date: '14 February 2026', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Lost', date: '7 October 2017', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Ramblers', result: 'Held', date: '15 October 2017', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Ramblers', result: 'Lost', date: '11 November 2017', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '19 November 2017', challenger: 'Drury' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '9 December 2017', challenger: 'Glenfield' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '22 February 2018', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '1 March 2018', challenger: 'Magpies' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '7 October 2018', challenger: 'Howick' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Lost', date: '13 October 2018', challenger: 'Magpies' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '27 October 2018', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '3 November 2018', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '11 November 2018', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '11 December 2018', challenger: 'Howick' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '13 December 2018', challenger: 'Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '22 December 2018', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '12 January 2019', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '22 January 2019', challenger: 'Papatoetoe' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Lost', date: '28 September 2019', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Patriots', result: 'Held', date: '5 October 2019', challenger: 'Howick' },
  { shield: 'Collen Callaghan Shield', holder: 'Patriots', result: 'Lost', date: '9 November 2019', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Ramblers', result: 'Lost', date: '16 November 2019', challenger: 'Magpies' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Held', date: '14 December 2019', challenger: 'Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Magpies', result: 'Lost', date: '14 January 2020', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '2 February 2020', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '31 October 2020', challenger: 'Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '21 November 2020', challenger: 'Howick' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Lost', date: '28 November 2020', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Lost', date: '12 December 2020', challenger: 'Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Marist', result: 'Lost', date: '9 January 2021', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '30 January 2021', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '20 February 2021', challenger: 'Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Lost', date: '20 February 2021', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '22 January 2022', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '1 March 2022', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '15 October 2022', challenger: 'Bandits' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '29 October 2022', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '23 November 2022', challenger: 'Metro' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '10 December 2022', challenger: 'Metro' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '11 February 2023', challenger: 'Howick' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '7 October 2023', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '14 October 2023', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Lost', date: '4 November 2023', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '11 November 2023', challenger: 'Alpha' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '21 November 2023', challenger: 'AU Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '25 November 2023', challenger: 'Metro' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Lost', date: '2 December 2023', challenger: 'Bandits' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '18 January 2024', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '25 January 2024', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '5 October 2024', challenger: 'AU Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '12 October 2024', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '19 October 2024', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '4 December 2024', challenger: 'Roosters' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Held', date: '8 December 2024', challenger: 'AU Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Bandits', result: 'Lost', date: '14 December 2024', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Held', date: '18 October 2025', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Otahuhu', result: 'Lost', date: '8 November 2025', challenger: 'Waitakere Bears' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '9 November 2025', challenger: 'Bandits' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '29 November 2025', challenger: 'Otahuhu' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '2 December 2025', challenger: 'AU Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '4 December 2025', challenger: 'Roosters' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '13 December 2025', challenger: 'Bandits' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '27 January 2026', challenger: 'AU Marist' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Held', date: '31 January 2026', challenger: 'Patriots' },
  { shield: 'Collen Callaghan Shield', holder: 'Waitakere Bears', result: 'Lost', date: '17 February 2026', challenger: 'Ramblers' },
  { shield: 'Collen Callaghan Shield', holder: 'Ramblers', result: 'Held', date: '24 February 2026', challenger: 'Bandits' },
]

// Latest recorded holder of each shield
export const SHIELD_HOLDERS: { shield: string; holder: string; since: string }[] = [
  { shield: 'Trevor Rouse Shield', holder: 'Auckland United', since: '14 February 2026' },
  { shield: 'Collen Callaghan Shield', holder: 'Ramblers', since: '24 February 2026' },
]
