// NFS officials — umpires and scorers. Generated from NFS_AFC_HISTORY.xlsx
// Career figures cover NFC, AFC and NFS, 2005–2026.

export type Official = { name: string; games: number; role: 'umpire' | 'scorer'; retired: boolean; level?: number }
export type OfficialMilestone = { name: string; games: number; tier: 100 | 200 | 300 | 400; season: string; role: 'umpire' | 'scorer' }

export const OFFICIALS: Official[] = [
  { name: 'Tama Howard', games: 404, role: 'umpire', retired: false },
  { name: 'Les Haslam', games: 361, role: 'umpire', retired: true },
  { name: 'Mark Porteous', games: 336, role: 'umpire', retired: false },
  { name: 'Heidi Leathart', games: 329, role: 'umpire', retired: false },
  { name: 'Chris Radford', games: 327, role: 'umpire', retired: false },
  { name: 'Lance Type', games: 305, role: 'umpire', retired: false },
  { name: 'Brydon Wells', games: 205, role: 'umpire', retired: false },
  { name: 'Jeff Weber', games: 197, role: 'umpire', retired: true },
  { name: 'Andrew McManus', games: 181, role: 'umpire', retired: false },
  { name: 'Andrew Laird', games: 169, role: 'umpire', retired: true },
  { name: 'Kam Meng Wong', games: 155, role: 'umpire', retired: false },
  { name: 'Dave Taiwhanga', games: 152, role: 'umpire', retired: false },
  { name: 'Riki Tourangi', games: 146, role: 'umpire', retired: true },
  { name: 'Lucy Pearcy', games: 143, role: 'umpire', retired: false },
  { name: 'Rob Sadgrove', games: 127, role: 'umpire', retired: false },
  { name: 'Heath Walker', games: 115, role: 'umpire', retired: true },
  { name: 'Judi Leaper', games: 107, role: 'umpire', retired: true },
  { name: 'John Hickman', games: 102, role: 'umpire', retired: false },
  { name: 'Simon Lindsay', games: 102, role: 'umpire', retired: false },
  { name: 'Glen Nalepa', games: 100, role: 'umpire', retired: true },
  { name: 'Paddy O\'Sullivan', games: 98, role: 'umpire', retired: false },
  { name: 'Richard Gale', games: 86, role: 'umpire', retired: false },
  { name: 'Matt Sneddon', games: 85, role: 'umpire', retired: false },
  { name: 'Shaun Poata', games: 85, role: 'umpire', retired: false },
  { name: 'Rebecca Taylor', games: 83, role: 'umpire', retired: false },
  { name: 'Kevin Sheehy', games: 79, role: 'umpire', retired: false },
  { name: 'Tarsh Raina-Nash', games: 49, role: 'umpire', retired: false },
  { name: 'Dowie Sutton', games: 46, role: 'umpire', retired: false },
  { name: 'Tony Irving', games: 46, role: 'umpire', retired: false },
  { name: 'Michael Smeath', games: 41, role: 'umpire', retired: false },
  { name: 'Anthony TeWhero', games: 40, role: 'umpire', retired: false },
  { name: 'Chris Boyce', games: 37, role: 'umpire', retired: false },
  { name: 'Martin Hunt', games: 35, role: 'umpire', retired: false },
  { name: 'Jo Edwin', games: 31, role: 'umpire', retired: false },
  { name: 'Dave Stevens', games: 27, role: 'umpire', retired: false },
  { name: 'Andrew Lawson', games: 27, role: 'umpire', retired: false },
  { name: 'Bill Smith', games: 24, role: 'umpire', retired: false },
  { name: 'Mike McCaw', games: 21, role: 'umpire', retired: false },
  { name: 'Manu Smith', games: 21, role: 'umpire', retired: false },
  { name: 'Taura Rountree', games: 19, role: 'umpire', retired: false },
  { name: 'Chris Murdoch', games: 18, role: 'umpire', retired: false },
  { name: 'Brody Donald', games: 14, role: 'umpire', retired: false },
  { name: 'Geoff Simmons', games: 13, role: 'umpire', retired: false },
  { name: 'Bridgette Baker', games: 13, role: 'umpire', retired: false },
  { name: 'Tony Cathro', games: 10, role: 'umpire', retired: false },
  { name: 'Michael Lee', games: 9, role: 'umpire', retired: false },
  { name: 'Tamati Montgomery', games: 7, role: 'umpire', retired: false },
  { name: 'Darrel Paul', games: 6, role: 'umpire', retired: false },
  { name: 'Dion Sneddon', games: 3, role: 'umpire', retired: false },
  { name: 'Hisan Kadal', games: 2, role: 'umpire', retired: false },
  { name: 'John Hall', games: 1, role: 'umpire', retired: false },
  { name: 'Lynnette Leathart', games: 333, role: 'scorer', retired: false, level: 7 },
  { name: 'Stuart Gamble', games: 215, role: 'scorer', retired: false, level: 7 },
  { name: 'Carolyn McQueen', games: 210, role: 'scorer', retired: false, level: 7 },
  { name: 'Christine Nukunuku', games: 183, role: 'scorer', retired: false, level: 7 },
  { name: 'Karina Rueb', games: 156, role: 'scorer', retired: false, level: 7 },
  { name: 'Deb Townley', games: 136, role: 'scorer', retired: false },
  { name: 'Tracee Topia', games: 126, role: 'scorer', retired: false },
  { name: 'Annie Martin', games: 106, role: 'scorer', retired: false },
  { name: 'Tania Irving', games: 99, role: 'scorer', retired: false },
  { name: 'Gwen Fletcher', games: 87, role: 'scorer', retired: false },
  { name: 'Flo Wanoa', games: 87, role: 'scorer', retired: false },
  { name: 'Linda Davies', games: 85, role: 'scorer', retired: false },
  { name: 'Harriet Tomlin', games: 84, role: 'scorer', retired: false },
  { name: 'Jan Hutchings', games: 79, role: 'scorer', retired: false },
  { name: 'Deb Douglas', games: 77, role: 'scorer', retired: false },
  { name: 'Harry Wooding', games: 72, role: 'scorer', retired: false },
  { name: 'Rowena McKenzie', games: 70, role: 'scorer', retired: false },
  { name: 'Charla Edwin', games: 62, role: 'scorer', retired: false },
  { name: 'Vanya Huntley', games: 59, role: 'scorer', retired: false },
  { name: 'Viti Flanagan', games: 53, role: 'scorer', retired: false },
  { name: 'Lil Natana', games: 46, role: 'scorer', retired: false },
  { name: 'Toby Charnley', games: 43, role: 'scorer', retired: false },
  { name: 'Ronnie Gurney', games: 43, role: 'scorer', retired: false },
  { name: 'Deb White', games: 40, role: 'scorer', retired: false },
  { name: 'Tania Sampson', games: 38, role: 'scorer', retired: false },
  { name: 'Tegan Edwin', games: 38, role: 'scorer', retired: false },
  { name: 'Andie McDowell', games: 38, role: 'scorer', retired: false },
  { name: 'Heidi Leathart', games: 35, role: 'scorer', retired: false },
  { name: 'Mel McFarlane', games: 35, role: 'scorer', retired: false },
  { name: 'Nicky Woon', games: 33, role: 'scorer', retired: false },
  { name: 'Jackie Hockley', games: 32, role: 'scorer', retired: false },
  { name: 'Cushla Stowers', games: 31, role: 'scorer', retired: false },
  { name: 'Priscilla Abraham', games: 31, role: 'scorer', retired: false },
  { name: 'Frances Harlick', games: 29, role: 'scorer', retired: false },
  { name: 'Carol Elson', games: 23, role: 'scorer', retired: false },
  { name: 'Deanna Callaghan', games: 20, role: 'scorer', retired: false },
  { name: 'Kris Jury', games: 18, role: 'scorer', retired: false },
  { name: 'Aimee Russell', games: 11, role: 'scorer', retired: false },
  { name: 'Raewyn Humphreys', games: 11, role: 'scorer', retired: false },
  { name: 'Laurelle Rogers', games: 11, role: 'scorer', retired: false },
  { name: 'Raelene Bishop', games: 6, role: 'scorer', retired: false },
  { name: 'Kelvin Chiles', games: 3, role: 'scorer', retired: false },
  { name: 'Suzette Taylor', games: 3, role: 'scorer', retired: false },
  { name: 'Megan Earley', games: 2, role: 'scorer', retired: false },
  { name: 'Linda Read', games: 1, role: 'scorer', retired: false },
  { name: 'Jill Gurden', games: 1, role: 'scorer', retired: false },
]

export const OFFICIAL_MILESTONES: OfficialMilestone[] = [
  { name: 'Lynnette Leathart', games: 119, tier: 100, season: '2013-14', role: 'scorer' },
  { name: 'Christine Nukunuku', games: 120, tier: 100, season: '2013-14', role: 'scorer' },
  { name: 'Carolyn McQueen', games: 115, tier: 100, season: '2014-15', role: 'scorer' },
  { name: 'Annie Martin', games: 106, tier: 100, season: '2016-17', role: 'scorer' },
  { name: 'Karina Rueb', games: 106, tier: 100, season: '2018-19', role: 'scorer' },
  { name: 'Tracee Topia', games: 105, tier: 100, season: '2019-20', role: 'scorer' },
  { name: 'Stuart Gamble', games: 108, tier: 100, season: '2021-22', role: 'scorer' },
  { name: 'Deb Townley', games: 112, tier: 100, season: '2023-24', role: 'scorer' },
  { name: 'Lynnette Leathart', games: 222, tier: 200, season: '2018-19', role: 'scorer' },
  { name: 'Carolyn McQueen', games: 210, tier: 200, season: '2024-25', role: 'scorer' },
  { name: 'Stuart Gamble', games: 215, tier: 200, season: '2025-26', role: 'scorer' },
  { name: 'Lynnette Leathart', games: 315, tier: 300, season: '2024-25', role: 'scorer' },
  { name: 'Les Haslam', games: 119, tier: 100, season: '2007-08', role: 'umpire' },
  { name: 'Jeff Weber', games: 101, tier: 100, season: '2007-08', role: 'umpire' },
  { name: 'Andrew Laird', games: 120, tier: 100, season: '2007-08', role: 'umpire' },
  { name: 'Mark Porteous', games: 121, tier: 100, season: '2011-12', role: 'umpire' },
  { name: 'Riki Tourangi', games: 146, tier: 100, season: '2012-13', role: 'umpire' },
  { name: 'Lance Type', games: 101, tier: 100, season: '2012-13', role: 'umpire' },
  { name: 'Chris Radford', games: 123, tier: 100, season: '2012-13', role: 'umpire' },
  { name: 'Glen Nalepa', games: 100, tier: 100, season: '2014-15', role: 'umpire' },
  { name: 'Brydon Wells', games: 106, tier: 100, season: '2015-16', role: 'umpire' },
  { name: 'Tama Howard', games: 128, tier: 100, season: '2015-16', role: 'umpire' },
  { name: 'Heath Walker', games: 115, tier: 100, season: '2016-17', role: 'umpire' },
  { name: 'Judi Leaper', games: 107, tier: 100, season: '2016-17', role: 'umpire' },
  { name: 'Heidi Leathart', games: 118, tier: 100, season: '2016-17', role: 'umpire' },
  { name: 'Andrew McManus', games: 119, tier: 100, season: '2017-18', role: 'umpire' },
  { name: 'Rob Sadgrove', games: 100, tier: 100, season: '2017-18', role: 'umpire' },
  { name: 'Kam Meng Wong', games: 110, tier: 100, season: '2023-24', role: 'umpire' },
  { name: 'John Hickman', games: 102, tier: 100, season: '2024-25', role: 'umpire' },
  { name: 'Dave Taiwhanga', games: 118, tier: 100, season: '2024-25', role: 'umpire' },
  { name: 'Lucy Pearcy', games: 106, tier: 100, season: '2024-25', role: 'umpire' },
  { name: 'Simon Lindsay', games: 102, tier: 100, season: '2025-26', role: 'umpire' },
  { name: 'Les Haslam', games: 222, tier: 200, season: '2010-11', role: 'umpire' },
  { name: 'Mark Porteous', games: 204, tier: 200, season: '2015-16', role: 'umpire' },
  { name: 'Chris Radford', games: 202, tier: 200, season: '2016-17', role: 'umpire' },
  { name: 'Lance Type', games: 210, tier: 200, season: '2017-18', role: 'umpire' },
  { name: 'Tama Howard', games: 205, tier: 200, season: '2017-18', role: 'umpire' },
  { name: 'Heidi Leathart', games: 207, tier: 200, season: '2020-21', role: 'umpire' },
  { name: 'Brydon Wells', games: 205, tier: 200, season: '2022-23', role: 'umpire' },
  { name: 'Les Haslam', games: 321, tier: 300, season: '2014-15', role: 'umpire' },
  { name: 'Mark Porteous', games: 300, tier: 300, season: '2018-19', role: 'umpire' },
  { name: 'Chris Radford', games: 310, tier: 300, season: '2020-21', role: 'umpire' },
  { name: 'Tama Howard', games: 306, tier: 300, season: '2021-22', role: 'umpire' },
  { name: 'Heidi Leathart', games: 307, tier: 300, season: '2024-25', role: 'umpire' },
  { name: 'Lance Type', games: 305, tier: 300, season: '2025-26', role: 'umpire' },
  { name: 'Tama Howard', games: 404, tier: 400, season: '2025-26', role: 'umpire' },
]
